// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "digitalsamba",
  "name": "DigitalSamba",
  "description": "DigitalSamba video conferencing plugin for Mattermost.",
  "homepage_url": "https://github.com/mattermost-community/mattermost-plugin-digitalsamba",
  "support_url": "https://github.com/mattermost-community/mattermost-plugin-digitalsamba/issues",
  "icon_path": "assets/icon.svg",
  "version": "1.0.6",
  "min_server_version": "5.2.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "DigitalSambaAPIKey",
        "display_name": "DigitalSamba API Key:",
        "type": "text",
        "help_text": "Your DigitalSamba API key. Get one at https://dashboard.digitalsamba.com",
        "placeholder": "ds_live_...",
        "default": null,
        "hosting": "",
        "secret": true
      },
      {
        "key": "DigitalSambaDashboardURL",
        "display_name": "DigitalSamba Dashboard URL:",
        "type": "text",
        "help_text": "The URL for your DigitalSamba dashboard API endpoint.",
        "placeholder": "https://api.digitalsamba.com",
        "default": "https://api.digitalsamba.com",
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaEmbedded",
        "display_name": "Embed DigitalSamba video inside Mattermost:",
        "type": "bool",
        "help_text": "When true, DigitalSamba video is embedded as a floating window inside Mattermost by default. Users can override this setting with '/digitalsamba settings'.",
        "placeholder": "",
        "default": true,
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaShowPrejoinPage",
        "display_name": "Show pre-join page:",
        "type": "bool",
        "help_text": "When false, pre-join page will not be displayed when DigitalSamba is embedded inside Mattermost.",
        "placeholder": "",
        "default": true,
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaNamingScheme",
        "display_name": "Meeting Names:",
        "type": "radio",
        "help_text": "Select how meeting names are generated by default. Users can override this setting with '/digitalsamba settings'.",
        "placeholder": "",
        "default": "words",
        "options": [
          {
            "display_name": "Random English words in title case (e.g. PlayfulDragonsObserveCuriously)",
            "value": "words"
          },
          {
            "display_name": "UUID (universally unique identifier)",
            "value": "uuid"
          },
          {
            "display_name": "Mattermost context specific names. Combination of team name, channel name, and random text in Public and Private channels; personal meeting name in Direct and Group Message channels.",
            "value": "mattermost"
          },
          {
            "display_name": "Allow user to select meeting name",
            "value": "ask"
          }
        ],
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaRoomExpiry",
        "display_name": "Room Expiry Time (minutes):",
        "type": "number",
        "help_text": "The number of minutes after which an unused room expires. Minimum is 30 minutes. Set to 0 for no expiry.",
        "placeholder": "",
        "default": 120,
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaMaxParticipants",
        "display_name": "Maximum Participants per Room:",
        "type": "number",
        "help_text": "Maximum number of participants allowed in a room (up to 2000).",
        "placeholder": "",
        "default": 100,
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaEnableRecording",
        "display_name": "Enable Recording:",
        "type": "bool",
        "help_text": "Allow meeting hosts to record meetings.",
        "placeholder": "",
        "default": false,
        "hosting": "",
        "secret": false
      },
      {
        "key": "DigitalSambaEnableBreakoutRooms",
        "display_name": "Enable Breakout Rooms:",
        "type": "bool",
        "help_text": "Allow meeting hosts to create breakout rooms.",
        "placeholder": "",
        "default": false,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
